sass:
  style: compressed

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: "assets/img"
    values:
      image: true

title: Enl_DM
name: Enl_DM's blog
description: Click the image above to view more.物以类聚人以群分,一个人被讨厌不是没有理由的

github: https://github.com/enldm
rss: true

plugins:
  - rouge
  - kramdown
  - jekyll-feed
  - jekyll-seo-tag
  - jemoji

exclude:
  - script
  - docs
  - vendor
  - Gemfile
  - Gemfile.lock
  
  show_excerpt: true
